version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  reviewers:
  - richo225
  assignees:
  - richo225
  ignore:
  - dependency-name: rubocop
    versions:
    - 1.7.0
    - 1.9.0
  - dependency-name: webmock
    versions:
    - 3.11.0
    - 3.11.2
  - dependency-name: cucumber
    versions:
    - 5.2.0
  - dependency-name: aruba
    versions:
    - 1.0.3
